server:
  port: 8000

spring:
  application:
    name: api-gateway-ex
  cloud:
    gateway:
      routes:
        - id: third-service
          uri: lb://eureka-client-ex
          predicates:
            - Path=/third-service/**
          filters:
            - CustomFilter
        - id: first-service
          uri: lb://FIRST-SERVICE-PRACTICE
#          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: second-service
          uri: lb://SECOND-SERVICE-PRACTICE
#          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
